databases:
  - name: backend-db
    databaseName: backend
    user: backend
    plan: free

services:
  - type: web
    name: backend-api
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: backend-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.render
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: CLOUDINARY_CLOUD_NAME
        value: dirmdexmb
      - key: CLOUDINARY_API_KEY
        value: "699357357128696"
      - key: CLOUDINARY_API_SECRET
        value: 81pKdnNZXDJ6KE9b1b8QxqB57e0
